global:
  name: consul
  datacenter: dc1
  image: hashicorp/consul:1.16.2

  tls:
    enabled: true

  peering:
    enabled: true

  acls:
    manageSystemACLs: true

  argocd:
    enabled: true

server:
  replicas: 3
  updatePartition: 2

connectInject:
  enabled: true

meshGateway:
  enabled: true