apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
spec:
  syncPolicy:
    # automated:
      # disable for demo purposes
      # prune: true
      # selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: consul
  sources:
    - chart: consul
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 1.1.5
      helm:
        releaseName: consul
        valueFiles:
          - $values/argocd/consul-helm-values.yaml
    - repoURL: 'https://github.com/joatmon08/consul-minikubes.git'
      targetRevision: argocd
      ref: values
    - repoURL: 'https://github.com/joatmon08/consul-minikubes.git'
      path: argocd/consul-config
      targetRevision: argocd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: consul